name = "workspace2-cron-trigger"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-05"

[vars]
GITHUB_OWNER = "mygithubtest02"
GITHUB_REPO = "ActionsWithCronTrigger"
GITHUB_WORKFLOW_FILE_NAME = "workspace2-translate.yml"
GITHUB_BRANCH = "master"

[triggers]
# crons = ["* * * * *"]
crons = []
